spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/taskmanagement
    username: root
    password: Pramo@153
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 6001

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:5000/eureka
